server {
    listen 8080;
    listen [::]:8080;
    server_name _;

    # Dung dan thu muc
    root /var/www/html/app;

    index index.htm index.html index.php;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000; # Kết nối tới PHP-FPM
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}