services:
 wp-app-alpine-ncc:
  image: wp-app-alpine-ncc
  container_name: wp-app-alpine-ncc
  init: true
  # network dev
  network_mode: "host"
  env_file:
   - .env
  # CMD => Dockerfile
  command: ["sh", "-c", "tail -f >/dev/null"]
